# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
fast_bilinear_cpp <- function(x, y, z, x0, y0) {
    .Call('_fitlandr_fast_bilinear_cpp', PACKAGE = 'fitlandr', x, y, z, x0, y0)
}

